[package]
name = "rv32i-mc-interpreter"
version = "0.1.0"
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
raw-cpuid = "7.0.3"
log = "0.4.8"
rasen = { git = "https://github.com/izik1/rasen", rev = "7a51b7e63aee73383a0507888256852ef3962e62" }
memmap = "0.7.0"
env_logger = "0.7.1"

[dev-dependencies]
insta = { version = "0.12.0", features = ["ron"] }
serde = "1.0.104"
