[package]
name = "rv32i-mc-interpreter"
version = "0.1.0"
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assembler = "0.10.1"
static_assertions = "1.1.0"
raw-cpuid = "7.0.3"

[patch.crates-io]
likely = { git = "https://github.com/izik1/likely", branch = "clippy-fix" }
assembler = { git = "https://github.com/izik1/assembler", branch = "clippy-fix" }
