[package]
name = "ribit"
description = "A Risc-V 32i-mc JIT"
version = "0.1.0"
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
raw-cpuid = "8.0.0"
log = "0.4.8"
rasen = { git = "https://github.com/izik1/rasen", rev = "1ad94d82305cf89f1f004a5e74a1334123306288" }
memmap = "0.7.0"
env_logger = "0.7.1"

[dev-dependencies]
insta = { version = "0.16.0" }
serde = "1.0.104"
