[workspace]

[package]
name = "ribit"
description = "A Risc-V 32i-mc JIT"
version = "0.1.0"
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"

[dependencies.goblin]
default-features = false
features = ["alloc", "elf32", "elf64", "endian_fd"]
version = "0.4.3"

[dependencies.env_logger]
default-features = false
version = "0.9.0"
features = ["termcolor", "atty", "humantime"]

[dependencies.ribit-core]
path = "ribit-core"

[dependencies.ribit-ssa]
path = "ribit-ssa"

[dependencies.ribit-jit]
path = "ribit-jit"

[dependencies.ribit-decode]
path = "ribit-decode"
