[package]
name = "rv32i-mc-interpreter"
version = "0.1.0"
authors = ["Zachery Gyurkovitz <zgyurkovitz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
