[package]
edition = "2021"
name = "ribit-asm"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.ribit-core]
path = "../ribit-core"

[dev-dependencies]
expect-test = "1.2.1"
